ALTER TABLE Reporte_del_negocio
ADD CONSTRAINT fk_reporte_del_negocio_historial_ingreso_del_negocio
FOREIGN KEY (Historial_ingreso_del_negocio_id) REFERENCES Historial_ingreso_del_negocio(Id_historial_ingreso);